//cpp
/* SHADOW translation unit -- generated by tools/tubuild.py create.
 * ov002/dM3dGLin  (2 function(s))
 *
 * NOT ENROLLED, NOT CANONICAL. This file contributes nothing to the ROM
 * build. It is a STARTING POINT (plan sec 7.3): local shadow declarations
 * below were carried verbatim from the legacy files, not reconciled against
 * real project headers -- that judgement call is left to a human/LLM review,
 * the way pilot #1 reconciled PoleLift::Render and ::CleanupResources by hand
 * (see notes/tu-reconstruction-pilot-report.md sec 5.2).
 *
 * FUNCTION ORDER IS DELIBERATELY THE REVERSE OF THE ROM'S -- mwccarm 2004/b56
 * emits one .text section per function, in the REVERSE of source order, so
 * the highest-address ROM function is written FIRST here. Do not reorder;
 * see notes/tu-reconstruction-pilot-report.md sec 3 for the one documented
 * exception (a destructor's D0/D1/D2 group has compiler-chosen order).
 *
 * Assembled from these legacy one-function sources (ROM address order):
 *   [0] 0x020fea84  src/_ZN8dM3dGLin3SetERK7Vector3S2_.cpp
 *   [1] 0x020feab8  src/_ZN8dM3dGLinD2Ev.cpp
 */

/* Includes: union of the legacy files', first-seen in ROM-ascending
 * processing order. NOT verified for header ordering constraints (e.g. a
 * common.h-before-X rule) -- watch for new compile errors after this. */
#include "dM3dGLin.h"

/* -------------------------------------------------------------------------- */
/* ROM ordinal 1 -- _ZN8dM3dGLinD2Ev, 0x020feab8, size 0x4 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN8dM3dGLinD2Ev
/* recovered: the out-of-line base-subobject destructor retained by the ROM */
dM3dGLin::~dM3dGLin()
{
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 0 -- _ZN8dM3dGLin3SetERK7Vector3S2_, 0x020fea84, size 0x34 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN8dM3dGLin3SetERK7Vector3S2_
/* recovered: real C++ method
 *
 * A line is exactly its two endpoints. The explicit component copies preserve
 * the ROM's interleaved load/store sequence while stating the geometry through
 * the class's proven Vector3 members.
 */
void dM3dGLin::Set(const Vector3 &start_, const Vector3 &end_)
{
    start.x = start_.x;
    start.y = start_.y;
    start.z = start_.z;
    end.x = end_.x;
    end.y = end_.y;
    end.z = end_.z;
}
