//cpp
/* SHADOW translation unit -- generated by tools/tubuild.py create.
 * ov002/daObjSwitch_c  (20 function(s))
 *
 * NOT ENROLLED, NOT CANONICAL. This file contributes nothing to the ROM
 * build. It is a STARTING POINT (plan sec 7.3): local shadow declarations
 * below were carried verbatim from the legacy files, not reconciled against
 * real project headers -- that judgement call is left to a human/LLM review,
 * the way pilot #1 reconciled PoleLift::Render and ::CleanupResources by hand
 * (see notes/tu-reconstruction-pilot-report.md sec 5.2).
 *
 * FUNCTION ORDER IS DELIBERATELY THE REVERSE OF THE ROM'S -- mwccarm 2004/b56
 * emits one .text section per function, in the REVERSE of source order, so
 * the highest-address ROM function is written FIRST here. Do not reorder;
 * see notes/tu-reconstruction-pilot-report.md sec 3 for the one documented
 * exception (a destructor's D0/D1/D2 group has compiler-chosen order).
 *
/* Includes: union of the legacy files', first-seen in ROM-ascending
 * processing order. NOT verified for header ordering constraints (e.g. a
 * common.h-before-X rule) -- watch for new compile errors after this. */
#include "daObjSwitch_c.h"
#include "decl_common.h"
#include "common.h"
#include "SharedFilePtr.h"
#include "dBgW.h"

/* Local shadow declarations carried from the legacy files verbatim.
 * NOT reconciled against real project headers -- check include/*.h for
 * each of these before compiling; a real header should usually win. */
/* shadow typedef 'Fix12i' */
typedef int Fix12i;

/* shadow enum 'Bool' */
enum Bool { FALSE, TRUE };

/* shadow typedef 'C' */
typedef struct C C;

/* shadow struct 'Base' */
struct Base { virtual void v0(); virtual void v1(); virtual void v2(); virtual void v3(); virtual void v4(); virtual void M(void*); };

extern "C" {
extern "C" int func_ov002_020ba4d8(char *c, int i);
extern "C" Fix12i _ZN4cstd4fdivEii(Fix12i a, Fix12i b);
extern int _ZN5Event8ClearBitEj(unsigned int n);
extern "C" void func_ov002_020ba01c(char* c, int mask, Fix12i b, Fix12i base, Fix12i target);
extern void _ZN5Sound9PlayBank3EjRK7Vector3(unsigned int n, void *v);
extern int func_02012310(int, int, int);
extern int data_0209b454;
extern signed char data_0209f2f8;
extern void _ZN8dActor_c13SpawnSoundObjEj(char* c, unsigned int n);
extern void _ZN5Event6SetBitEj(unsigned int b);
extern unsigned char DecIfAbove0_Byte(unsigned char *p);
void UnloadSilverStarAndNumber(void);
extern char data_ov002_0211092c;
extern unsigned char IsAreaShowing(int idx);
extern void *_ZN8dActor_c10FindWithIDEj(unsigned int id);
extern void _ZN10dBgActor_c21UpdateModelPosAndRotYEv(char *c);
extern int _ZN10dBgActor_c13IsClsnInRangeE5Fix12IiES1_(char *c, int a, int b);
extern int _ZN5Sound17ChangeMusicVolumeEj5Fix12IiE(unsigned int id, int vol);
void LoadSilverStarAndNumber(void);
int _ZN5Model8LoadFileER13SharedFilePtr(int p);
void _ZN9ModelBase7SetFileEP8BMD_Fileii(void *self, int f, int a, int b);
void func_ov002_020b9f80(char *self);
int _ZN7dBgW_Kc8LoadFileER13SharedFilePtr(int p);
void _ZN10dBgW_KcMbg7SetFileEP8KCL_FileRK9Matrix4x35Fix12IiEsR10CLPS_Block(
void *self, int f, void *mtx, int fix, s16 s, int clps);
void func_020393c4(void *p, void *v);
extern char data_ov002_021098e8[];
extern char data_ov002_021098ec[];
extern char data_ov002_021098f0[];
extern int func_ov002_020baa98;
/* TUBUILD CONFLICT -- alternate declaration of func_ov002_020ba4d8, from the legacy file for func_ov002_020ba0bc, NOT applied: extern int func_ov002_020ba4d8(); */
/* TUBUILD CONFLICT -- alternate declaration of _ZN5Event8ClearBitEj, from the legacy file for func_ov002_020ba0f8, NOT applied: extern void _ZN5Event8ClearBitEj(unsigned int n); */
/* TUBUILD CONFLICT -- alternate declaration of func_ov002_020ba4d8, from the legacy file for func_ov002_020ba0f8, NOT applied: extern "C" void func_ov002_020ba4d8(void* c, int i); */
/* TUBUILD CONFLICT -- alternate declaration of func_ov002_020ba4d8, from the legacy file for func_ov002_020ba1ac, NOT applied: extern void func_ov002_020ba4d8(char* c, int i); */
/* TUBUILD CONFLICT -- alternate declaration of func_ov002_020ba01c, from the legacy file for func_ov002_020ba2d0, NOT applied: extern void func_ov002_020ba01c(char* c, int a, int b, int fix, int e); */
/* TUBUILD CONFLICT -- alternate declaration of _ZN5Sound9PlayBank3EjRK7Vector3, from the legacy file for func_ov002_020ba2d0, NOT applied: extern void _ZN5Sound9PlayBank3EjRK7Vector3(unsigned int a, void* v); */
/* TUBUILD CONFLICT -- alternate declaration of func_ov002_020ba4d8, from the legacy file for func_ov002_020ba2d0, NOT applied: extern void func_ov002_020ba4d8(char* c, int i); */
/* TUBUILD CONFLICT -- alternate declaration of func_ov002_020ba4d8, from the legacy file for func_ov002_020ba3a8, NOT applied: extern void func_ov002_020ba4d8(C *c, int i); */
/* TUBUILD CONFLICT -- alternate declaration of func_ov002_020ba01c, from the legacy file for _ZN13daObjSwitch_c8BehaviorEv, NOT applied: extern void func_ov002_020ba01c(char *c, int mask, int b, int base, int target); */
/* TUBUILD CONFLICT -- alternate declaration of _ZN5Event8ClearBitEj, from the legacy file for _ZN13daObjSwitch_c13InitResourcesEv, NOT applied: void _ZN5Event8ClearBitEj(unsigned int b); */
/* TUBUILD CONFLICT -- alternate declaration of _ZN10dBgActor_c21UpdateModelPosAndRotYEv, from the legacy file for _ZN13daObjSwitch_c13InitResourcesEv, NOT applied: void _ZN10dBgActor_c21UpdateModelPosAndRotYEv(void *self); */
/* TUBUILD CONFLICT -- alternate declaration of data_ov002_0211092c, from the legacy file for _ZN13daObjSwitch_c13InitResourcesEv, NOT applied: extern int data_ov002_0211092c; */
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 19 -- _ZN13daObjSwitch_c13InitResourcesEv, 0x020ba83c, size 0x1f0 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN13daObjSwitch_c13InitResourcesEv
int daObjSwitch_c::InitResources()
{
    u8 idx;
    int f;

    mDrawScaleX = 0x1000;
    mDrawScaleY = 0x1000;
    mDrawScaleZ = 0x1000;
    mTargetActorID = 0;
    mTargetActor = 0;
    mHomeAreaId = mAreaId;

    {
        int b = 0;
        if (actorID == 0xc) b = 1;
        if (b) {
            mFlags |= 0x4000000;
            mSwitchType = 2;
            unk_351 = param1;
            if (unk_351 == 0xff)
                unk_351 = 0;
            mTimeLimit = (param1 >> 8) & 0xff;
            LoadSilverStarAndNumber();
            _ZN5Model8LoadFileER13SharedFilePtr((int)&data_ov002_0211092c);
            mResourceIdx = 1;
        } else {
            mSwitchType = param1 & 3;
            mEventBit = (param1 >> 3) & 0xf;
            mTimeLimit = (param1 >> 8) & 0xff;
            _ZN5Event8ClearBitEj(mEventBit);
            mResourceIdx = 0;
        }
    }

    idx = mResourceIdx;
    f = _ZN5Model8LoadFileER13SharedFilePtr(*(int*)(data_ov002_021098e8 + idx * 0xc));
    _ZN9ModelBase7SetFileEP8BMD_Fileii(&mModel, f, 1, -1);
    _ZN10dBgActor_c21UpdateModelPosAndRotYEv((char *)this);
    func_ov002_020b9f80((char *)this);

    idx = mResourceIdx;
    f = _ZN7dBgW_Kc8LoadFileER13SharedFilePtr(*(int*)(data_ov002_021098ec + idx * 0xc));
    _ZN10dBgW_KcMbg7SetFileEP8KCL_FileRK9Matrix4x35Fix12IiEsR10CLPS_Block(
        &mMeshCollider, f, &mClsnMat, 0x199, mAngleY,
        *(int*)(data_ov002_021098f0 + idx * 0xc));

    func_020393c4(&mMeshCollider, &func_ov002_020baa98);

    {
        u16 h = mTimeLimit;
        if (h == 0xff || h == 0)
            mTimeLimit = 0x190;
        else
            mTimeLimit *= 0xa;
    }
    unk_34f = 5;
    mPosY += 0x5000;
    mMusicFadeDone = 1;
    return 1;
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 18 -- _ZN13daObjSwitch_c8BehaviorEv, 0x020ba624, size 0x218 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN13daObjSwitch_c8BehaviorEv
/* recovered: named members + shared header, real C++ method, declarations from a shared header */
/* recovered: named members + shared header, real C++ method */
int daObjSwitch_c::Behavior()
{
    void *a;
    int id344;
    int v;

    if (IsAreaShowing(mHomeAreaId) == 0) {
        mAreaId = mHomeAreaId;
        mTimer = 1;
        func_ov002_020ba01c(((char *)this), 2, 1, 0x333, 0x1000);
        func_ov002_020ba4d8(((char *)this), 0);
        a = _ZN8dActor_c10FindWithIDEj(mTargetActorID);
        if (a != 0) {
            func_ov002_020e6d88(a);
        }
    }

    {
        int isType = (int)(actorID == 0xc);
        if (isType != 0) {
            if (func_ov002_020b9f00(((char *)this)) != 0) {
                a = _ZN8dActor_c10FindWithIDEj(mTargetActorID);
                if (a != 0) {
                    mTargetActor = (s32)a;
                }
            }
        }
    }

    if ((int)(actorID == 0xc) != 0) {
        id344 = mTargetActorID;
        if (id344 == 0) {
            func_ov002_020ba01c(((char *)this), 2, 3, 0x333, 0x1000);
            _ZN10dBgActor_c21UpdateModelPosAndRotYEv(((char *)this));
            if (_ZN10dBgActor_c13IsClsnInRangeE5Fix12IiES1_(((char *)this), 0, 0) != 0) {
                func_ov002_020b9f80(((char *)this));
            }
            return 1;
        }
        if (_ZN8dActor_c10FindWithIDEj(id344) == 0) {
            mTargetActorID = 0;
            mAreaId = mHomeAreaId;
            return 1;
        }
    }

    if ((data_0209b454 & 0x4000000) == 0) {
        mTimer++;
    }
    func_ov002_020ba520(((char *)this));
    _ZN10dBgActor_c21UpdateModelPosAndRotYEv(((char *)this));
    if (_ZN10dBgActor_c13IsClsnInRangeE5Fix12IiES1_(((char *)this), 0, 0) != 0) {
        func_ov002_020b9f80(((char *)this));
    }

    if (mSwitchType == 2) {
        if (mMusicFadeDone == 0) {
            v = mMusicVolume;
            if (v != 0x40) {
                if (v == 0x7f) {
                    if ((data_0209b454 & 0x4000000) == 0) {
                        mMusicFadeDone = _ZN5Sound17ChangeMusicVolumeEj5Fix12IiE(v, 0x64cc);
                    }
                }
            } else {
                mMusicFadeDone = _ZN5Sound17ChangeMusicVolumeEj5Fix12IiE(v, 0xc999);
            }
        }
    }

    unk_350 = 0;
    return 1;
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 17 -- _ZN13daObjSwitch_c6RenderEv, 0x020ba5f4, size 0x30 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN13daObjSwitch_c6RenderEv
/* recovered: named members + shared header, real C++ method */
int daObjSwitch_c::Render()
{
  ((Base *)&(*(u8 *)&mModel))->M((char *)&mDrawScaleX);
  return 1;
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 16 -- _ZN13daObjSwitch_c16CleanupResourcesEv, 0x020ba568, size 0x8c */
/* -------------------------------------------------------------------------- */
// @symbol _ZN13daObjSwitch_c16CleanupResourcesEv
/* recovered: named members + shared header, real C++ method */
// _ZN13daObjSwitch_c16CleanupResourcesEv at 0x020ba568
// Matched byte-for-byte with mwccarm 1.2/sp2p3 (ov002).
int daObjSwitch_c::CleanupResources()
{
    int t;
    if (((dBgW *)&mMeshCollider)->IsEnabled()) {
        ((dBgW *)&mMeshCollider)->Disable();
    }
    ((SharedFilePtr *)(*(void**)(data_ov002_021098e8 + mResourceIdx * 0xc)))->Release();
    ((SharedFilePtr *)(*(void**)(data_ov002_021098ec + mResourceIdx * 0xc)))->Release();
    t = actorID == 0xc;
    if (t != false) {
        UnloadSilverStarAndNumber();
        ((SharedFilePtr *)(&data_ov002_0211092c))->Release();
    }
    return 1;
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 15 -- func_ov002_020ba520, 0x020ba520, size 0x48 */
/* -------------------------------------------------------------------------- */
// @symbol func_ov002_020ba520
struct C; typedef void (C::*PMF)();
struct Entry { PMF pmf[2]; };
extern Entry data_ov002_0210e00c[];
struct C { char pad[0x340]; int idx; };
extern "C" void func_ov002_020ba520(char *cc) { C *c = (C *)cc; int j = c->idx; (c->*data_ov002_0210e00c[j].pmf[1])(); }

/* -------------------------------------------------------------------------- */
/* ROM ordinal 14 -- func_ov002_020ba4d8, 0x020ba4d8, size 0x48 */
/* -------------------------------------------------------------------------- */
// @symbol func_ov002_020ba4d8
/* Uses the C/PMF/Entry view from the func_ov002_020ba520 section above (identical layout: pad 0x340 + idx, PMF pair); redeclaring them here is a redefinition. */
extern "C" int func_ov002_020ba4d8(char *cc, int i) { C *c = (C *)cc; c->idx = i; int j = c->idx; (c->*data_ov002_0210e00c[j].pmf[0])(); }

/* -------------------------------------------------------------------------- */
/* ROM ordinal 13 -- func_ov002_020ba4c0, 0x020ba4c0, size 0x18 */
/* -------------------------------------------------------------------------- */
// @symbol func_ov002_020ba4c0
// recovered name: PushBlock_Kill
/* recovered: renamed to Class_Method */
/* daObjPowerUpItem_c::Kill - recovered from vtable slot identity */
extern "C" {  /* .c-derived member: C linkage for the whole block */
void func_ov002_020ba4c0(char *p)
{
    *(short *)(p + 0x338) = 0;
    *(char *)(p + 0x34f) = 5;
}
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 12 -- func_ov002_020ba3fc, 0x020ba3fc, size 0xc4 */
/* -------------------------------------------------------------------------- */
// @symbol func_ov002_020ba3fc
struct dActor_c;
extern "C" {
extern struct dActor_c* _ZN8dActor_c15FindWithActorIDEjPS_(unsigned id, struct dActor_c* prev);
void func_ov002_020ba3fc(char* c) {
    int ok = 1;
    struct dActor_c* p;
    *(short*)(c+0x338) = 0;
    *(unsigned char*)(c+0x34f) = 5;
    *(unsigned char*)(c+0x34d) = 0;
    p = _ZN8dActor_c15FindWithActorIDEjPS_(0xb, 0);
    while (p != 0) {
        if (p != (struct dActor_c*)c) {
            if (*(int*)((char*)p+0x340) != 0) ok = 0;
        }
        p = _ZN8dActor_c15FindWithActorIDEjPS_(0xb, p);
    }
    if (ok != 0) {
        p = _ZN8dActor_c15FindWithActorIDEjPS_(0xc, 0);
        while (p != 0) {
            if (p != (struct dActor_c*)c) {
                if (*(int*)((char*)p+0x340) != 0) ok = 0;
            }
            p = _ZN8dActor_c15FindWithActorIDEjPS_(0xc, p);
        }
    }
    if (ok != 0) *(int*)(c+0x334) = 0x7f;
}
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 11 -- func_ov002_020ba3a8, 0x020ba3a8, size 0x54 */
/* -------------------------------------------------------------------------- */
// @symbol func_ov002_020ba3a8
extern "C" {  /* .c-derived member: C linkage for the whole block */
void func_ov002_020ba3a8(C *c){
  if(*(unsigned char*)((char*)c+0x350)){
    if(DecIfAbove0_Byte((unsigned char*)((char*)c+0x34f))!=0) return;
    func_ov002_020ba4d8((char *)c,1);
    return;
  }
  *(unsigned char*)((char*)c+0x34f)=5;
}
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 10 -- func_ov002_020ba2d0, 0x020ba2d0, size 0xd8 */
/* -------------------------------------------------------------------------- */
// @symbol func_ov002_020ba2d0
extern "C" {  /* .c-derived member: C linkage for the whole block */
void func_ov002_020ba2d0(char* c){
  func_ov002_020ba01c(c, 2, 3, 0x1000, 0x333);
  if(*(unsigned short*)(c+0x300+0x38) != 3) return;
  _ZN5Sound9PlayBank3EjRK7Vector3(0x3e, c+0x74);
  if((int)(*(unsigned short*)(c+0xc) == 0xc) != 0){
    char* p = *(char**)(c+0x348);
    if(p != 0){
      func_ov002_020e7104(p, 1);
      *(signed char*)(c+0xcc) = -1;
    }
  }else{
    if(data_0209f2f8 == 0xd && *(int*)(c+0x5c) == -0x140000){
      _ZN8dActor_c13SpawnSoundObjEj(c, 0);
    }
    _ZN5Event6SetBitEj(*(unsigned char*)(c+0x34e));
  }
  func_ov002_020ba4d8(c, 2);
}
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 9 -- func_ov002_020ba2ac, 0x020ba2ac, size 0x24 */
/* -------------------------------------------------------------------------- */
// @symbol func_ov002_020ba2ac
extern "C" {  /* .c-derived member: C linkage for the whole block */
void func_ov002_020ba2ac(char *p)
{
    *(short *)(p + 0x338) = 0;
    *(char *)(p + 0x34f) = 5;
    *(char *)(p + 0x34d) = 0;
    *(int *)(p + 0x334) = 64;
}
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 8 -- func_ov002_020ba1ac, 0x020ba1ac, size 0x100 */
/* -------------------------------------------------------------------------- */
// @symbol func_ov002_020ba1ac
extern "C" {  /* .c-derived member: C linkage for the whole block */
void func_ov002_020ba1ac(char* self) {
    int diff;
    if (*(int*)(self + 0x33c) == 0) return;
    if (*(int*)(self + 0x33c) == 1) {
        if (*(unsigned char*)(self + 0x350) == 0) {
            func_ov002_020ba4d8(self, 3);
            return;
        }
    }
    diff = *(unsigned short*)(self + 0x33a) - *(unsigned short*)(self + 0x338);
    if (!(data_0209b454 & 0x4000000)) {
        if (diff == 0x2d) {
            *(int*)(self + 0x330) = 0;
        } else if (diff < 0x2d) {
            *(int*)(self + 0x330) = func_02012310(*(int*)(self + 0x330), 0x39, 0);
        } else {
            *(int*)(self + 0x330) = func_02012310(*(int*)(self + 0x330), 0x38, 0);
        }
    }
    if (*(unsigned short*)(self + 0x338) > *(unsigned short*)(self + 0x33a)) {
        func_ov002_020ba4d8(self, 4);
        return;
    }
    if (*(int*)(self + 0x348) == 0) return;
    if (*(int*)(*(int*)(self + 0x348) + 0x440) != 5) return;
    func_ov002_020ba4d8(self, 4);
}
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 7 -- func_ov002_020ba0f8, 0x020ba0f8, size 0xb4 */
/* -------------------------------------------------------------------------- */
// @symbol func_ov002_020ba0f8
/* recovered: shared common types, declarations from a shared header */
/* recovered: shared common types */
extern "C" void func_ov002_020ba0f8(char* c) {
    func_ov002_020ba01c(c, 2, 3, 0x333, 0x1000);
    if (*(unsigned short*)(c + 0x338) != 3) return;
    _ZN5Sound9PlayBank3EjRK7Vector3(0x3e, (struct Vector3*)(c + 0x74));
    {
        int b = (*(unsigned short*)(c + 0xc) == 0xc);
        if (b) {
            char* p = *(char**)(c + 0x348);
            if (p != 0 && *(int*)(p + 0x438) == 0) {
                func_ov002_020e7104(p, 0);
            }
            *(unsigned char*)(c + 0xcc) = *(signed char*)(c + 0x353);
        } else {
            _ZN5Event8ClearBitEj(*(unsigned char*)(c + 0x34e));
        }
    }
    func_ov002_020ba4d8(c, 0);
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 6 -- func_ov002_020ba0bc, 0x020ba0bc, size 0x3c */
/* -------------------------------------------------------------------------- */
// @symbol func_ov002_020ba0bc
extern "C" {  /* .c-derived member: C linkage for the whole block */
int func_ov002_020ba0bc(char* c){
    unsigned short v = *(unsigned short*)(c+0xc);
    enum Bool b = (enum Bool)(v==0xc);
    if(!b) _ZN5Event8ClearBitEj(*(unsigned char*)(c+0x34e));
    return func_ov002_020ba4d8(c, 3);
}
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 5 -- func_ov002_020ba01c, 0x020ba01c, size 0xa0 */
/* -------------------------------------------------------------------------- */
// @symbol func_ov002_020ba01c
extern "C" void func_ov002_020ba01c(char* c, int mask, Fix12i b, Fix12i base, Fix12i target){
  Fix12i d = _ZN4cstd4fdivEii((Fix12i)*(unsigned short*)(c+0x338), b);
  Fix12i diff = target - base;
  Fix12i e = (Fix12i)(((long long)diff * d + 0x800) >> 12);
  Fix12i v = base + _ZN4cstd4fdivEii(e, 0x1000);
  Fix12i h = (Fix12i)(((long long)v * 0x3c000 + 0x800) >> 12);
  *(Fix12i*)(c+0x32c) = 0x3c000 - h;
  if (mask & 1) *(Fix12i*)(c+0x320) = v;
  if (mask & 2) *(Fix12i*)(c+0x324) = v;
  if (mask & 4) *(Fix12i*)(c+0x328) = v;
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 4 -- _ZN13daObjSwitch_c15OnGroundPoundedER8dActor_c, 0x020b9fec, size 0x30 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN13daObjSwitch_c15OnGroundPoundedER8dActor_c
/* recovered: named members + shared header, real C++ method, declarations from a shared header */
/* recovered: named members + shared header, real C++ method */
void daObjSwitch_c::OnGroundPounded(dActor_c &other)
{
    if (unk_340 != 0) return;
    func_ov002_020ba4d8(((char *)this), 1);
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 3 -- func_ov002_020b9f80, 0x020b9f80, size 0x6c */
/* -------------------------------------------------------------------------- */
// @symbol func_ov002_020b9f80
// @symbol func_ov002_020b9f80
/* recovered: shared common types */
#include "common.h"
extern "C" {

struct MMC { char p[0x124]; };
struct Obj { char p[0x2ec]; Matrix4x3 m; };
int _ZN10dBgW_KcMbg9TransformERK9Matrix4x3s(MMC*, Matrix4x3&, short);
void func_ov002_020b9f80(char* self){
    Obj* o = (Obj*)self;
    /* Same 12-word copy the legacy file's flat-Matrix4x3 struct assignment
       produced (this TU sees the nested spelling via daObjSwitch_c.h, so the
       copy is spelled through a layout-identical local type). */
    struct M43flat { s32 m[12]; };
    *(struct M43flat *)&o->m = *(struct M43flat *)(self + 0xf0);
    *(int*)(self+0x310) = *(int*)(self+0x5c);
    *(int*)(self+0x314) = *(int*)(self+0x60) - *(int*)(self+0x32c);
    *(int*)(self+0x318) = *(int*)(self+0x64);
    _ZN10dBgW_KcMbg9TransformERK9Matrix4x3s((MMC*)(self+0x124), o->m, *(short*)(self+0x8e));
}
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 2 -- func_ov002_020b9f00, 0x020b9f00, size 0x80 */
/* -------------------------------------------------------------------------- */
// @symbol func_ov002_020b9f00
extern "C" {  /* .c-derived member: C linkage for the whole block */
int func_ov002_020b9f00(char* r5) {
    void* r1;
    if (*(int*)(r5 + 0x344)) return 0;
    r1 = _ZN8dActor_c15FindWithActorIDEjPS_(0xb2, 0);
    while (r1) {
        if (*(unsigned char*)(r5 + 0x351) == *(unsigned char*)((char*)r1 + 0x49d)) {
            *(int*)(r5 + 0x344) = *(int*)((char*)r1 + 4);
            return 1;
        }
        r1 = _ZN8dActor_c15FindWithActorIDEjPS_(0xb2, (struct dActor_c *)r1);
    }
    return 0;
}
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 1 -- _ZN13daObjSwitch_cD0Ev, 0x020b9ea8, size 0x58 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN13daObjSwitch_cD0Ev
/* recovered: real C++ deleting destructor -- the compiler emits the whole body
 *
 * D0 is the DELETING destructor: destroy through this class and its bases --
 * which is why more than one vptr store appears -- then return the object to
 * its heap. Nobody writes that; declaring `~daObjSwitch_c()` is enough, because mwcc
 * emits D2, D0 and D1 together and objisolate keeps the one this file is bound
 * to.
 *
 * The deallocation is an inline operator delete, which is why nothing below
 * mentions a heap.
 *
 * (No out-of-line definition here: the header carries the single inline
 * definition for the merged TU; the compiler emits D0 from the visible body.)
 */

/* -------------------------------------------------------------------------- */
/* ROM ordinal 0 -- _ZN13daObjSwitch_cD1Ev, 0x020b9e64, size 0x44 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN13daObjSwitch_cD1Ev
/* recovered: real C++ destructor -- the compiler emits the whole body
 * from the inline definition in include/daObjSwitch_c.h (single definition
 * for the merged TU; the D0 section's out-of-line copy is removed for
 * the same reason).
 *
 * Two vtable stores and three destructor calls, every one a consequence of
 * `struct daObjSwitch_c : dBgActor_c`: its own vptr, then dBgActor_c's -- inlined,
 * because dBgActor_c's destructor is defined in its class body -- then
 * dBgActor_c's Model and dBgW_KcMbg, then dActor_c. This class adds no
 * member with a destructor of its own.
 */
